deps: Upgrade rules_distroless to 0.4.3
The reason for the upgrade is because the //:lock target of the
apt repository checks for bazel marker files to write the lockfile
at the right relative path from the root module.

In 0.3.8, only WORKSPACE and WORKSPACE.bazel files were checked
as marker files, and since we are full bzlmod with a single
MODULE.bazel marker file, the run target would fail like so:

```bash
> bazel run @neuron_bookworm//:lock
Writing lockfile to runtimes/neuron/packages.lock.json
Error: neither WORKSPACE nor WORKSPACE.bazel file was found
```

0.4.3 brings that support.