fix(build): location of bash in NixOS
Without this fix we see the following errors on NixOS:

```
bazel run //examples/mnist
Extracting Bazel installation...
Starting local Bazel server (9.1.1) and connecting to it...
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 126
/bin/sh: tools/workspace_status.sh: /bin/bash: bad interpreter: No such file or directory
INFO: Elapsed time: 10.601s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target
```

This is because in NixOS `bash` is not in `/bin/bash`.